insert into team (Nazev) values ('Meezzy');
insert into team (Nazev) values ('Zoomcast');
insert into team (Nazev) values ('Quimba');
insert into team (Nazev) values ('Kwilith');
insert into team (Nazev) values ('Topicblab');
insert into team (Nazev) values ('Jaxbean');
insert into team (Nazev) values ('Pixoboo');
insert into team (Nazev) values ('Photofeed');
insert into team (Nazev) values ('Thoughtstorm');
insert into team (Nazev) values ('Youfeed');
insert into team (Nazev) values ('Gabspot');
insert into team (Nazev) values ('Vinder');
insert into team (Nazev) values ('Kwideo');
insert into team (Nazev) values ('Feedbug');
insert into team (Nazev) values ('Zoozzy');
insert into team (Nazev) values ('Yakijo');
insert into team (Nazev) values ('Realpoint');
insert into team (Nazev) values ('Camido');
insert into team (Nazev) values ('Yoveo');
insert into team (Nazev) values ('Voonder');
insert into team (Nazev) values ('Bubblebox');


insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (10, 9, 20, 13, '2020-01-29');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (13, 9, 13, 11, '2020-01-21');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (20, 3, 18, 24, '2020-01-19');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (6, 11, 16, 2, '2020-01-28');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (8, 5, 4, 23, '2020-01-28');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (7, 17, 7, 18, '2020-01-27');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (3, 18, 5, 3, '2020-01-22');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (4, 19, 17, 15, '2020-01-25');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (12, 2, 25, 25, '2020-01-18');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (11, 15, 15, 12, '2020-01-21');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (20, 16, 4, 2, '2020-01-21');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (19, 16, 14, 14, '2020-01-23');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (16, 1, 21, 8, '2020-01-23');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (2, 3, 25, 1, '2020-01-20');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (4, 19, 15, 18, '2020-01-21');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (3, 4, 3, 3, '2020-01-29');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (16, 21, 14, 19, '2020-01-22');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (13, 2, 5, 24, '2020-01-19');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (12, 16, 16, 6, '2020-01-26');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (19, 16, 22, 2, '2020-01-26');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (12, 20, 20, 10, '2020-01-18');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (17, 11, 7, 6, '2020-01-28');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (1, 3, 11, 23, '2020-01-24');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (14, 9, 25, 2, '2020-01-21');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (11, 17, 18, 2, '2020-01-22');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (15, 11, 5, 17, '2020-01-27');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (17, 18, 16, 2, '2020-01-22');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (18, 14, 18, 4, '2020-01-25');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (21, 15, 3, 25, '2020-01-17');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (21, 4, 4, 2, '2020-01-22');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (15, 7, 15, 24, '2020-01-23');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (10, 10, 4, 15, '2020-01-29');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (21, 14, 20, 9, '2020-01-27');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (18, 21, 15, 17, '2020-01-24');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (4, 7, 4, 7, '2020-01-26');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (5, 5, 3, 19, '2020-01-18');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (5, 2, 12, 7, '2020-01-25');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (4, 14, 21, 5, '2020-01-27');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (12, 3, 5, 8, '2020-01-21');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (21, 12, 23, 20, '2020-01-27');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (6, 9, 4, 6, '2020-01-28');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (9, 16, 12, 15, '2020-01-23');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (4, 13, 6, 5, '2020-01-20');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (1, 14, 25, 18, '2020-01-19');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (14, 10, 20, 12, '2020-01-19');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (19, 6, 20, 24, '2020-01-28');
insert into zapas (Domaci_id, Hoste_id, Hoste_body, Domaci_body, Datum) values (6, 8, 17, 16, '2020-01-27');


insert into hrac (Jmeno, Prijmenni, TeamId) values ('Othelia', 'Jex', 15);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Duky', 'Cianelli', 19);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Dill', 'Mateo', 20);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Irena', 'Wearing', 16);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Mariya', 'Camolli', 7);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Fay', 'Wilks', 19);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Ida', 'Byneth', 11);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Dori', 'Wolfers', 2);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Kellyann', 'Indgs', 2);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Merrielle', 'McCreedy', 1);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Sergent', 'Kryska', 18);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Ardith', 'Geeraert', 11);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Wendeline', 'Deschelle', 7);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Cherilynn', 'Zamora', 14);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Heinrik', 'Cauthra', 15);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Georgetta', 'Torpie', 8);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Lin', 'Swainson', 21);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Fleming', 'Scipsey', 8);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Letisha', 'Abbatt', 7);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Dionisio', 'Bossel', 11);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Jerry', 'O''Shiels', 21);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Kylie', 'Shercliff', 3);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Stephannie', 'Chawkley', 7);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Margalo', 'Pedlar', 19);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Rene', 'Brauns', 4);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Pascale', 'Sapp', 20);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Annice', 'Alfonzo', 21);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Tadd', 'MacClure', 21);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Candy', 'Lefwich', 14);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Etheline', 'Crother', 2);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Teddy', 'Matfin', 5);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Kaleena', 'Coraini', 2);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Crichton', 'Garrie', 3);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Abramo', 'Pittford', 2);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Chariot', 'Brinklow', 4);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Janeva', 'Abatelli', 12);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Holli', 'Pringle', 17);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Libbey', 'Linskill', 8);
insert into hrac (Jmeno, Prijmenni, TeamId) values ('Gilbertine', 'Hansmann', 2);
