/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marti
 */
public class FilterForm extends javax.swing.JFrame {

    /**
     * Creates new form FilterForm
     */
    public FilterForm() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField2 = new java.awt.TextField();
        textSearch = new java.awt.TextField();
        buttonSubmit = new java.awt.Button();
        textYearFrom = new java.awt.TextField();
        textDateFrom = new java.awt.TextField();
        textMonthFrom = new java.awt.TextField();
        textDayTo = new java.awt.TextField();
        textMonthTo = new java.awt.TextField();
        textYearTo = new java.awt.TextField();
        labelTo = new java.awt.Label();
        labelFrom = new java.awt.Label();

        textField2.setText("textField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textSearch.setText("Search");
        textSearch.setSelectionEnd(textSearch.getText().length());

        buttonSubmit.setActionCommand("okButton");
        buttonSubmit.setLabel("OK");
        buttonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSubmitMouseClicked(evt);
            }
        });
        buttonSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonSubmitKeyPressed(evt);
            }
        });

        textYearFrom.setText("Year");
        textYearFrom.setSelectionEnd(textYearFrom.getText().length());

        textDateFrom.setText("Day");
        textDateFrom.setSelectionEnd(textDateFrom.getText().length());

        textMonthFrom.setText("Month");
        textMonthFrom.setSelectionEnd(textMonthFrom.getText().length());

        textDayTo.setText("Day");
        textDayTo.setSelectionEnd(textDayTo.getText().length());

        textMonthTo.setText("Month");
        textMonthTo.setSelectionEnd(textMonthTo.getText().length());

        textYearTo.setText("Year");
        textYearTo.setSelectionEnd(textYearTo.getText().length());

        labelTo.setText("To date");

        labelFrom.setText("From date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(textDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textMonthFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                textYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup().addGroup(layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textDayTo, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textMonthTo, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textYearTo, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(labelFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textMonthFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textMonthTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textDayTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textYearTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                .addComponent(textSearch, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmitMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonSubmitMouseClicked
        // TODO add your handling code here:

        Main.dateFromFilter = Main
                .toFormatedDate(textDateFrom.getText() + "." + textMonthFrom.getText() + "." + textYearFrom.getText());
        Main.dateToFilter = Main
                .toFormatedDate(textDayTo.getText() + "." + textMonthTo.getText() + "." + textYearTo.getText());
        Main.fileFilter = textSearch.getText();
        Main.init();
        this.dispose();

    }// GEN-LAST:event_buttonSubmitMouseClicked

    private void buttonSubmitKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_buttonSubmitKeyPressed
        // TODO add your handling code here:
        Main.dateFromFilter = Main
                .toFormatedDate(textDateFrom.getText() + "." + textMonthFrom.getText() + "." + textYearFrom.getText());
        Main.dateToFilter = Main
                .toFormatedDate(textDayTo.getText() + "." + textMonthTo.getText() + "." + textYearTo.getText());
        Main.fileFilter = textSearch.getText();
        Main.init();
        this.dispose();
    }// GEN-LAST:event_buttonSubmitKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonSubmit;
    private java.awt.Label labelFrom;
    private java.awt.Label labelTo;
    private java.awt.TextField textDateFrom;
    private java.awt.TextField textDayTo;
    private java.awt.TextField textField2;
    private java.awt.TextField textMonthFrom;
    private java.awt.TextField textMonthTo;
    private java.awt.TextField textSearch;
    private java.awt.TextField textYearFrom;
    private java.awt.TextField textYearTo;
    // End of variables declaration//GEN-END:variables
}
